"""empty message

Revision ID: 5029b0a14c06
Revises: 0712aece8651
Create Date: 2018-10-06 17:59:28.818259

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5029b0a14c06'
down_revision = '0712aece8651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:  # https://stackoverflow.com/a/31140916/973425
        batch_op.drop_column('marksheet_grad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('marksheet_grad', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
